### ISSUE TITLE
Can't install msgpack :(((((((

### ISSUE THREAD

**Issue by camilleeyries** [pgriess/node-msgpack#67]
I got this error when I try to do _npm install msgpack_

I have try with all the versions of nodejs...

``` shell
mbp-de-camille-2:server Camille$ npm install msgpack clean
npm WARN package.json mini-map-server@0.0.1 No repository field.
npm WARN package.json mini-map-server@0.0.1 No README data

> msgpack@0.2.7 install /Users/Camille/Desktop/agar-mini-map/server/node_modules/msgpack
> node-gyp rebuild

  CXX(target) Release/obj.target/libmsgpack/deps/msgpack/gcc_atomic.o
  CXX(target) Release/obj.target/libmsgpack/deps/msgpack/object.o
  CC(target) Release/obj.target/libmsgpack/deps/msgpack/objectc.o
  CC(target) Release/obj.target/libmsgpack/deps/msgpack/unpack.o
../deps/msgpack/unpack.c:59:43: warning: missing field 'via' initializer
      [-Wmissing-field-initializers]
{ msgpack_object o = { MSGPACK_OBJECT_NIL }; return o; }
                                          ^
1 warning generated.
  CC(target) Release/obj.target/libmsgpack/deps/msgpack/vrefbuffer.o
  CC(target) Release/obj.target/libmsgpack/deps/msgpack/zone.o
  CC(target) Release/obj.target/libmsgpack/deps/msgpack/version.o
  LIBTOOL-STATIC Release/msgpack.a
  CXX(target) Release/obj.target/msgpackBinding/src/msgpack.o
In file included from ../src/msgpack.cc:9:
../node_modules/nan/nan.h:324:27: error: redefinition of
      'NanEnsureHandleOrPersistent'
  NAN_INLINE v8::Local<T> NanEnsureHandleOrPersistent(const v8::Local<T> &val) {
                          ^
../node_modules/nan/nan.h:319:17: note: previous definition is here
  v8::Handle<T> NanEnsureHandleOrPersistent(const v8::Handle<T> &val) {
                ^
../node_modules/nan/nan.h:344:27: error: redefinition of 'NanEnsureLocal'
  NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Handle<T> &val) {
                          ^
../node_modules/nan/nan.h:334:27: note: previous definition is here
  NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Local<T> &val) {
                          ^
../node_modules/nan/nan.h:757:13: error: no member named 'smalloc' in namespace
      'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
../node_modules/nan/nan.h:768:12: error: no matching function for call to 'New'
    return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
           ^~~~~~~~~~~~~~~~~
/Users/Camille/.node-gyp/4.2.4/include/node/node_buffer.h:31:40: note: 
      candidate function not viable: no known conversion from 'uint32_t'
      (aka 'unsigned int') to 'enum encoding' for 3rd argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/Camille/.node-gyp/4.2.4/include/node/node_buffer.h:43:40: note: 
      candidate function not viable: 2nd argument ('const char *') would lose
      const qualifier
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/Camille/.node-gyp/4.2.4/include/node/node_buffer.h:28:40: note: 
      candidate function not viable: requires 2 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                       ^
/Users/Camille/.node-gyp/4.2.4/include/node/node_buffer.h:36:40: note: 
      candidate function not viable: requires 5 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
In file included from ../src/msgpack.cc:9:
../node_modules/nan/nan.h:772:12: error: no viable conversion from
      'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object>'
    return node::Buffer::New(v8::Isolate::GetCurrent(), size);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/Camille/.node-gyp/4.2.4/include/node/v8.h:210:7: note: candidate
      constructor (the implicit copy constructor) not viable: no known
      conversion from 'v8::MaybeLocal<v8::Object>' to 'const
      v8::Local<v8::Object> &' for 1st argument
class Local {
      ^
/Users/Camille/.node-gyp/4.2.4/include/node/v8.h:210:7: note: candidate
      constructor (the implicit move constructor) not viable: no known
      conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object> &&'
      for 1st argument
class Local {
      ^
/Users/Camille/.node-gyp/4.2.4/include/node/v8.h:214:13: note: candidate
      template ignored: could not match 'Local' against 'MaybeLocal'
  V8_INLINE Local(Local<S> that)
            ^
/Users/Camille/.node-gyp/4.2.4/include/node/v8.h:326:13: note: candidate
      template ignored: could not match 'S *' against
      'v8::MaybeLocal<v8::Object>'
  V8_INLINE Local(S* that)
            ^
In file included from ../src/msgpack.cc:9:
../node_modules/nan/nan.h:779:26: error: no member named 'Use' in namespace
      'node::Buffer'
    return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
           ~~~~~~~~~~~~~~^
../src/msgpack.cc:155:50: warning: 'DecodeBytes' is deprecated: Use
      DecodeBytes(isolate, ...) [-Wdeprecated-declarations]
        mo->via.raw.size = static_cast<uint32_t>(DecodeBytes(v8obj, UTF8));
                                                 ^
/Users/Camille/.node-gyp/4.2.4/include/node/node.h:318:32: note: 'DecodeBytes'
      has been explicitly marked deprecated here
                inline ssize_t DecodeBytes(
                               ^
/Users/Camille/.node-gyp/4.2.4/include/node/node.h:66:42: note: expanded from
      macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^
../src/msgpack.cc:158:9: warning: 'DecodeWrite' is deprecated: Use
      DecodeWrite(isolate, ...) [-Wdeprecated-declarations]
        DecodeWrite((char*) mo->via.raw.ptr, mo->via.raw.size, v8obj, UTF8);
        ^
/Users/Camille/.node-gyp/4.2.4/include/node/node.h:331:32: note: 'DecodeWrite'
      has been explicitly marked deprecated here
                inline ssize_t DecodeWrite(char* buf,
                               ^
/Users/Camille/.node-gyp/4.2.4/include/node/node.h:66:42: note: expanded from
      macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^
../src/msgpack.cc:165:50: warning: 'DecodeBytes' is deprecated: Use
      DecodeBytes(isolate, ...) [-Wdeprecated-declarations]
        mo->via.raw.size = static_cast<uint32_t>(DecodeBytes(result, UTF8));
                                                 ^
/Users/Camille/.node-gyp/4.2.4/include/node/node.h:318:32: note: 'DecodeBytes'
      has been explicitly marked deprecated here
                inline ssize_t DecodeBytes(
                               ^
/Users/Camille/.node-gyp/4.2.4/include/node/node.h:66:42: note: expanded from
      macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^
../src/msgpack.cc:168:9: warning: 'DecodeWrite' is deprecated: Use
      DecodeWrite(isolate, ...) [-Wdeprecated-declarations]
        DecodeWrite((char*) mo->via.raw.ptr, mo->via.raw.size, result, UTF8);
        ^
/Users/Camille/.node-gyp/4.2.4/include/node/node.h:331:32: note: 'DecodeWrite'
      has been explicitly marked deprecated here
                inline ssize_t DecodeWrite(char* buf,
                               ^
/Users/Camille/.node-gyp/4.2.4/include/node/node.h:66:42: note: expanded from
      macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^
../src/msgpack.cc:316:32: error: no matching function for call to
      'NanNewBufferHandle'
    Local<Object> slowBuffer = NanNewBufferHandle(
                               ^~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:754:36: note: candidate function not viable: no known
      conversion from 'void (char *, void *)' to 'int' for 3rd argument
  NAN_INLINE v8::Local<v8::Object> NanNewBufferHandle (
                                   ^
../node_modules/nan/nan.h:764:36: note: candidate function not viable: requires
      2 arguments, but 4 were provided
  NAN_INLINE v8::Local<v8::Object> NanNewBufferHandle (
                                   ^
../node_modules/nan/nan.h:771:36: note: candidate function not viable: requires
      single argument 'size', but 4 arguments were provided
  NAN_INLINE v8::Local<v8::Object> NanNewBufferHandle (uint32_t size) {
                                   ^
In file included from ../src/msgpack.cc:1:
/Users/Camille/.node-gyp/4.2.4/include/node/v8.h:221:5: error: assigning to
      'v8::Primitive *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/Camille/.node-gyp/4.2.4/include/node/v8.h:180:37: note: expanded from
      macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:501:12: note: in instantiation of function template
      specialization 'v8::Local<v8::Primitive>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
           ^
../node_modules/nan/nan.h:483:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(Nan::imp::NanEnsureLocal(val))
                             ^
In file included from ../src/msgpack.cc:1:
/Users/Camille/.node-gyp/4.2.4/include/node/v8.h:221:5: error: assigning to
      'v8::Boolean *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/Camille/.node-gyp/4.2.4/include/node/v8.h:180:37: note: expanded from
      macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:511:12: note: in instantiation of function template
      specialization 'v8::Local<v8::Boolean>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
           ^
../node_modules/nan/nan.h:483:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(Nan::imp::NanEnsureLocal(val))
                             ^
In file included from ../src/msgpack.cc:1:
/Users/Camille/.node-gyp/4.2.4/include/node/v8.h:221:5: error: assigning to
      'v8::Function *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/Camille/.node-gyp/4.2.4/include/node/v8.h:180:37: note: expanded from
      macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1645:12: note: in instantiation of function template
      specialization 'v8::Local<v8::Function>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
           ^
../node_modules/nan/nan.h:483:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(Nan::imp::NanEnsureLocal(val))
                             ^
In file included from ../src/msgpack.cc:1:
/Users/Camille/.node-gyp/4.2.4/include/node/v8.h:221:5: error: assigning to
      'v8::Object *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/Camille/.node-gyp/4.2.4/include/node/v8.h:180:37: note: expanded from
      macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1776:12: note: in instantiation of function template
      specialization 'v8::Local<v8::Object>::Local<v8::Value>' requested here
    return NanEscapeScope(
           ^
../node_modules/nan/nan.h:483:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(Nan::imp::NanEnsureLocal(val))
                             ^
4 warnings and 11 errors generated.
make: *** [Release/obj.target/msgpackBinding/src/msgpack.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/Camille/.nvm/versions/node/v4.2.4/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/Users/Camille/.nvm/versions/node/v4.2.4/bin/node" "/Users/Camille/.nvm/versions/node/v4.2.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Camille/Desktop/agar-mini-map/server/node_modules/msgpack
gyp ERR! node -v v4.2.4
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/Camille/.nvm/versions/node/v4.2.4/bin/node" "/Users/Camille/.nvm/versions/node/v4.2.4/bin/npm" "install" "msgpack" "clean"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! msgpack@0.2.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the msgpack@0.2.7 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the msgpack package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls msgpack
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Camille/Desktop/agar-mini-map/server/npm-debug.log

```

**Comment by AgarioCheats** [comment]
Yes, I believe it has something to do with running on different OS. Windows msgpack does not work, but on ubuntu it does.

**Comment by camilleeyries** [comment]
It work with node 0.12

**Comment by StarpTech** [comment]
@AgarioCheats Yes, msgpack does not work on windows. I tried everything.
